name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: build
        run: make

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: build/H.hex
          
      - name: prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          files: build/H.hex
